### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by nostromo200** [ibm-cloud-docs/citrix-netscaler-vpx#3]
Link to "Netscaler available versions" not working : http://downloads.softlayer.local/citrix/netscaler/

**Comment by lilorozco** [comment]
I think you need to be connected to the SoftLayer VPN to access the link above. I see: 
![image](https://user-images.githubusercontent.com/19810032/42057675-bc895e90-7ae3-11e8-93f9-0db58bdbaad7.png)

@jbmitch we should say that you must be connected to the IBM Cloud Infrastructure VPN in order to access the link

**Comment by jbmitch** [comment]
Yep, put in a note. Will close this out when it replicates.
