### ISSUE TITLE
Need Information about Different Licenses Offered

### ISSUE THREAD

**Issue by kintulpatadia** [ibm-cloud-docs/citrix-netscaler-vpx#9]
We need a breakdown of the difference between platinum vs standard, please see the attached pdf from Citrix website with the breakdown. 

[netscaler-data-sheet-full.pdf](https://github.com/IBM-Bluemix-Docs/citrix-netscaler-vpx/files/2465382/netscaler-data-sheet-full.pdf)

**Comment by jbmitch** [comment]
Hi @kintulpatadia, we do offer some of this info in this topi: https://console.test.cloud.ibm.com/docs/infrastructure/loadbalancer-service/explore-load-balancers.html

You have to scroll the table over to the right in order to see the Platinum information. 

If this isn't sufficient, I'd be happy to put a link to the Citrix PDF you have here on their website, if you can provide it. We don't want to source a Citrix PDF like this on our side, because then we have to maintain it (monitor and update it with a new version whenever Citrix updates theirs), so linking to it is best. We link to a lot of Citrix supplemental material in the VPX docs already. We also don't want to transfer the information into IBM Cloud Docs, as 1) it's too much info for our content and 2) because of the previous problem with double sourcing content.

**Comment by kintulpatadia** [comment]
What you mentioned just shows the difference between the LBs we offer but not the license for Netscalers, please see the link - https://www.citrix.com/content/dam/citrix/en_us/documents/products-solutions/netscaler-data-sheet-full.pdfKintul PatadiaTechnical Client Success ManagerWatson and Cloud Platform Address: 14001 Dallas Pkwy Suite M100 | Dallas, TX 75240Mobile: 972-839-2472E-mail: kpatadia@us.ibm.com-----jbmitch <notifications@github.com> wrote: -----To: IBM-Bluemix-Docs/citrix-netscaler-vpx <citrix-netscaler-vpx@noreply.github.com>From: jbmitch <notifications@github.com>Date: 10/15/2018 11:34AMCc: kintulpatadia <kpatadia@us.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [IBM-Bluemix-Docs/citrix-netscaler-vpx] Need Information about Different Licenses Offered (#9)Hi @kintulpatadia, we do offer some of this info in this topi: https://console.test.cloud.ibm.com/docs/infrastructure/loadbalancer-service/explore-load-balancers.htmlYou have to scroll the table over to the right in order to see the Platinum information.If this isn't sufficient, I'd be happy to put a link to the Citrix PDF you have here on their website, if you can provide it. We don't want to source a Citrix PDF like this on our side, because then we have to maintain it (monitor and update it with a new version whenever Citrix updates theirs), so linking to it is best. We link to a lot of Citrix supplemental material in the VPX docs already. We also don't want to transfer the information into IBM Cloud Docs, as 1) it's too much info for our content and 2) because of the previous problem with double sourcing content.

**Comment by jbmitch** [comment]
@kintulpatadia Okay, as I said, happy to add the link into the docs for you.
